Repository bitnami/containers, pull requests merged in 2022-09, with the labels that each got.

#4816 [bitnami/istio-pilot, istio-proxyv2] chore: :fire: Remove containers
  bitnami/istio-pilot/1.13/debian-11/Dockerfile
  bitnami/istio-pilot/1.13/debian-11/docker-compose.yml
  bitnami/istio-pilot/1.13/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/istio-pilot/1.13/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/istio-pilot/1.13/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/istio-pilot/1.13/debian-11/tags-info.yaml
  bitnami/istio-pilot/1.14/debian-11/Dockerfile
  bitnami/istio-pilot/1.14/debian-11/docker-compose.yml
  bitnami/istio-pilot/1.14/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/istio-pilot/1.14/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/istio-pilot/1.14/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/istio-pilot/1.14/debian-11/tags-info.yaml
  bitnami/istio-pilot/README.md
  bitnami/istio-pilot/docker-compose.yml
  bitnami/istio-proxyv2/1.13/debian-11/Dockerfile
  bitnami/istio-proxyv2/1.13/debian-11/docker-compose.yml
  bitnami/istio-proxyv2/1.13/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/istio-proxyv2/1.13/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/istio-proxyv2/1.13/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/istio-proxyv2/1.13/debian-11/tags-info.yaml
  bitnami/istio-proxyv2/1.14/debian-11/Dockerfile
  bitnami/istio-proxyv2/1.14/debian-11/docker-compose.yml
  bitnami/istio-proxyv2/1.14/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/istio-proxyv2/1.14/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/istio-proxyv2/1.14/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/istio-proxyv2/1.14/debian-11/tags-info.yaml
  bitnami/istio-proxyv2/README.md
  bitnami/istio-proxyv2/docker-compose.yml
Labels: bitnami

#4975 [bitnami/kubeapps-kubeops] Add deprecation notice
  bitnami/kubeapps-kubeops/README.md
Labels: bitnami

#4318 [bitnami/openldap] Follow LDAP_LOGLEVEL in setup phase
  bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh
Labels: verify, in-progress, openldap

#4982 [bitnami/pytorch-intel] Remove old branches
  bitnami/pytorch-intel/1.10/debian-11/Dockerfile
  bitnami/pytorch-intel/1.10/debian-11/docker-compose.yml
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libbitnami.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libcomponent.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libfile.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libhook.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/liblog.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libos.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libservice.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libvalidations.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libversion.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/opt/bitnami/scripts/libwebserver.sh
  bitnami/pytorch-intel/1.10/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/pytorch-intel/1.10/debian-11/rootfs/opt/bitnami/scripts/pytorch/entrypoint.sh
  bitnami/pytorch-intel/1.10/debian-11/rootfs/opt/bitnami/scripts/pytorch/postunpack.sh
  bitnami/pytorch-intel/1.12/debian-11/Dockerfile
  bitnami/pytorch-intel/1.12/debian-11/docker-compose.yml
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libbitnami.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libcomponent.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libfile.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libhook.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/liblog.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libos.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libservice.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libvalidations.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libversion.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/opt/bitnami/scripts/libwebserver.sh
  bitnami/pytorch-intel/1.12/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/pytorch-intel/1.12/debian-11/rootfs/opt/bitnami/scripts/pytorch/entrypoint.sh
  bitnami/pytorch-intel/1.12/debian-11/rootfs/opt/bitnami/scripts/pytorch/postunpack.sh
  bitnami/pytorch-intel/1.12/debian-11/tags-info.yaml
Labels: bitnami

#4766 [bitnami/*] Containers CI Automated PRs should follow same matrix approach as regular PRs
  .github/workflows/ci-automated-pipeline.yaml
  .github/workflows/ci-pipeline.yaml
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
Labels: bitnami

#3395 [bitnami/etcd] Fix libetcd.sh - unbound ETCD_ACTIVE_ENDPOINTS
  bitnami/etcd/3.3/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
  bitnami/etcd/3.4/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
  bitnami/etcd/3.5/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
Labels: verify, in-progress, etcd

#4990 [bitnami/redis-cluster] Support scenario where IPs are reused
  bitnami/redis-cluster/6.2/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh
  bitnami/redis-cluster/7.0/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh
Labels: verify, in-progress, redis-cluster

#5007 Fix running openldap as $LDAP_DAEMON_USER
  bitnami/openldap/2.5/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh
  bitnami/openldap/2.6/debian-11/rootfs/opt/bitnami/scripts/libopenldap.sh
Labels: verify, in-progress, openldap

#5585 [bitnami/*] Add CD step to retrieve registry credentials
  .github/workflows/cd-pipeline.yaml
Labels: verify

#5914 [bitnami/*] Fix skipped CDs for automated PRs when pusher != bitnami-bot
  .github/workflows/cd-pipeline.yaml
Labels: verify, bitnami

#5928 [bitnami/mongodb-sharded][bitnami/rabbitmq] Remove ARM support
  .vib/mongodb-sharded/vib-publish.json
  .vib/rabbitmq/vib-publish.json
Labels: verify, bitnami

#6208 [bitnami/golang] Deprecate branch 1.17
  bitnami/golang/1.17/debian-11/Dockerfile
  bitnami/golang/1.17/debian-11/docker-compose.yml
  bitnami/golang/1.17/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/golang/1.17/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/golang/1.17/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/golang/1.17/debian-11/tags-info.yaml
  bitnami/golang/README.md
Labels: verify, bitnami

#4174 [bitnami/discourse] Add support for Redis connections with SSL
  bitnami/discourse/2/debian-11/rootfs/opt/bitnami/scripts/discourse-env.sh
  bitnami/discourse/2/debian-11/rootfs/opt/bitnami/scripts/libdiscourse.sh
  bitnami/discourse/README.md
Labels: verify, in-progress, discourse

#6368 Replace Wordpress with Discourse
  bitnami/discourse/README.md
Labels: verify, triage, discourse

#6418 [bitnami/*] Split workflow responsibilites
  .github/workflows/cd-pipeline.yml
  .github/workflows/ci-pipeline.yml
  .github/workflows/comments.yml
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
  .github/workflows/stale.yml
  .github/workflows/triage.yml
Labels: verify, bitnami

#6622 [bitnami/clickhouse] Add VIB files
  .vib/clickhouse/vib-publish.json
  .vib/clickhouse/vib-verify.json
Labels: verify, bitnami

#6637 [bitnami/*] Create new column in support dashboard for failed automated PRs
  .github/workflows/.env
  .github/workflows/ci-pipeline.yml
  .github/workflows/comments.yml
  .github/workflows/moving-cards.yml
  .github/workflows/triage.yml
Labels: verify, bitnami

#6669 [bitnami/sonarqube] Add ARM64 support for Sonarqube
  .vib/sonarqube/vib-publish.json
Labels: bitnami

#6679 [bitnami/*] Follow up #6637, Fix moving-cards workflow
  .github/workflows/moving-cards.yml
Labels: verify, bitnami

#6698 [bitnami/*]Avoid (re)assignment of closed cards
  .github/workflows/moving-cards.yml
Labels: verify, bitnami

#6739 [bitnami/**] Fix/moving cards issue
  .github/workflows/moving-cards.yml
Labels: verify

#6980 [bitnami/*] Update publishing registry
  .github/workflows/cd-pipeline.yml
Labels: verify, bitnami

#6987 [bitnami/*] Fix workflow's description typo
  .github/workflows/cd-pipeline.yml
Labels: verify, bitnami

#7074 [bitnami/*] Fix label issue when verify is already set
  .github/workflows/ci-pipeline.yml
Labels: verify, bitnami

#7079 [bitnami/*] Fix verification summary
  .github/workflows/ci-pipeline.yml
Labels: verify, bitnami

#7340 Add PRs note to the contributing guidelines
  CONTRIBUTING.md
Labels: verify, bitnami

#6700 [bitnami/moodle] Fix MOODLE_SSLPROXY and MOODLE_REVERSEPROXY
  bitnami/moodle/3/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh
  bitnami/moodle/4/debian-11/rootfs/opt/bitnami/scripts/libmoodle.sh
Labels: verify, in-progress, moodle

#6978 [bitnami/mongodb] Fix hardcoded root username for metrics user creation
  bitnami/mongodb/5.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh
  bitnami/mongodb/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh
Labels: verify, in-progress, mongodb, mongodb-sharded

#6996 [bitnami/mongodb-sharded] Fix hardcoded root username for metrics user creation
  bitnami/mongodb-sharded/5.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh
  bitnami/mongodb-sharded/6.0/debian-11/rootfs/opt/bitnami/scripts/libmongodb.sh
Labels: verify, in-progress, mongodb-sharded

#7568 Adds missing vib folder for inc-tensorlflow-intel
  .vib/inc-tensorflow-intel/vib-publish.json
  .vib/inc-tensorflow-intel/vib-verify.json
Labels: verify, bitnami

#7861 [bitnami/ksql bitnami/schema-registry] Deprecate branch 6.0
  bitnami/ksql/6.0/debian-11/Dockerfile
  bitnami/ksql/6.0/debian-11/docker-compose.yml
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libbitnami.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libfile.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libhook.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/liblog.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libos.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libservice.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libvalidations.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libversion.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libwebserver.sh
  bitnami/ksql/6.0/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/java/entrypoint.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/java/postunpack.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/ksql-env.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/ksql/entrypoint.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/ksql/postunpack.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/ksql/run.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/ksql/setup.sh
  bitnami/ksql/6.0/debian-11/rootfs/opt/bitnami/scripts/libksql.sh
  bitnami/ksql/6.0/debian-11/tags-info.yaml
  bitnami/ksql/README.md
  bitnami/schema-registry/6.0/debian-11/Dockerfile
  bitnami/schema-registry/6.0/debian-11/docker-compose.yml
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/licenses/licenses.txt
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libbitnami.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libfile.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libfs.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libhook.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/liblog.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libos.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libservice.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libvalidations.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libversion.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/opt/bitnami/scripts/libwebserver.sh
  bitnami/schema-registry/6.0/debian-11/prebuildfs/usr/sbin/install_packages
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/java/entrypoint.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/java/postunpack.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/libschemaregistry.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/schema-registry-env.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/schema-registry/entrypoint.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/schema-registry/postunpack.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/schema-registry/run.sh
  bitnami/schema-registry/6.0/debian-11/rootfs/opt/bitnami/scripts/schema-registry/setup.sh
  bitnami/schema-registry/6.0/debian-11/tags-info.yaml
  bitnami/schema-registry/README.md
Labels: verify, bitnami

#7065 [bitnami/zookeeper] add zookeeper peerType,observer
  bitnami/zookeeper/3.6/debian-11/rootfs/opt/bitnami/scripts/libzookeeper.sh
  bitnami/zookeeper/3.6/debian-11/rootfs/opt/bitnami/scripts/zookeeper-env.sh
  bitnami/zookeeper/3.7/debian-11/rootfs/opt/bitnami/scripts/libzookeeper.sh
  bitnami/zookeeper/3.7/debian-11/rootfs/opt/bitnami/scripts/zookeeper-env.sh
  bitnami/zookeeper/3.8/debian-11/rootfs/opt/bitnami/scripts/libzookeeper.sh
  bitnami/zookeeper/3.8/debian-11/rootfs/opt/bitnami/scripts/zookeeper-env.sh
  bitnami/zookeeper/README.md
Labels: verify, in-progress, zookeeper

#8084 [bitnami/containers] Fix label assignment issue
  .github/workflows/moving-cards.yml
Labels: verify, bitnami

#8099 [bitnami/containers] Fix issue retrieving issue number
  .github/workflows/moving-cards.yml
Labels: verify, bitnami

#8103 [bitnami/containers] Human friendly name for assign-label job
  .github/workflows/assign-labels.yml
Labels: verify, bitnami

#8170 [bitnami/*] Add publishing registry
  .github/workflows/cd-pipeline-harbor.yml
Labels: verify, bitnami

#8318 [bitnami/*] Rename Assign Asset Label workflow file and remove unnecessary '/'
  .github/workflows/assign-asset-label.yml
Labels: verify, bitnami

#8190 [bitnami/postgresql-repmgr] Adds a new environment variable to set failover in repmgr
  bitnami/postgresql-repmgr/10/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh
  bitnami/postgresql-repmgr/10/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh
  bitnami/postgresql-repmgr/11/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh
  bitnami/postgresql-repmgr/11/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh
  bitnami/postgresql-repmgr/12/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh
  bitnami/postgresql-repmgr/12/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh
  bitnami/postgresql-repmgr/13/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh
  bitnami/postgresql-repmgr/13/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh
  bitnami/postgresql-repmgr/14/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh
  bitnami/postgresql-repmgr/14/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh
  bitnami/postgresql-repmgr/README.md
Labels: verify, in-progress, postgresql-repmgr
