Repository bitnami/containers, pull requests merged in 2024-11, with the labels that each got.

#74090 [bitnami/valkey-sentinel] Update tests to check the master to primary change in the configuration
  .vib/valkey-sentinel/goss/valkey-sentinel.yaml
Labels: verify, bitnami

#73235 [bitnami/drupal] Fix problem in getting database port on second run in libdrupal.sh
  bitnami/drupal/10/debian-12/rootfs/opt/bitnami/scripts/libdrupal.sh
  bitnami/drupal/11/debian-12/rootfs/opt/bitnami/scripts/libdrupal.sh
Labels: verify, in-progress, drupal

#74875 [bitnami/*] test: :white_check_mark: Update endpoint test url
  .vib/common/goss/templates/check-ca-certs.yaml
  .vib/ruby/goss/ruby.yaml
Labels: verify, bitnami

#74887 [bitnami/statsd-exporter] ci: VIB tests
  .vib/statsd-exporter/goss/goss.yaml
  .vib/statsd-exporter/goss/vars.yaml
  .vib/statsd-exporter/vib-verify.json
Labels: verify, bitnami

#74969 [bitnami/kibana] Add sed-in-place exception
  .vib/kibana/goss/vars.yaml
Labels: verify, bitnami

#75006 [bitnami/jaeger] test: :white_check_mark: Skip jaeger version in 2.0.0
  .vib/jaeger/goss/vars.yaml
Labels: verify, bitnami

#75031 [bitnami/prometheus] Console* paths only available for Prometheus 2.y.z
  .vib/prometheus/goss/prometheus.yaml
  .vib/prometheus/goss/vars.yaml
Labels: verify, bitnami

#74972 [bitnami/schema-registry] Relax ssl options verifications in schema registry
  bitnami/schema-registry/7.4/debian-12/rootfs/opt/bitnami/scripts/libschemaregistry.sh
  bitnami/schema-registry/7.5/debian-12/rootfs/opt/bitnami/scripts/libschemaregistry.sh
  bitnami/schema-registry/7.6/debian-12/rootfs/opt/bitnami/scripts/libschemaregistry.sh
  bitnami/schema-registry/7.7/debian-12/rootfs/opt/bitnami/scripts/libschemaregistry.sh
Labels: verify, in-progress, schema-registry

#75114 [bitnami/postgresql] Update README.md
  bitnami/postgresql/README.md
Labels: verify, in-progress, postgresql

#75222 [bitnami/java] Load entrypoint.sh for tests
  .vib/java/goss/java.yaml
Labels: verify, bitnami

#75257 [bitnami/appsmith] Update GOSS tests for version 1.49.0
  .vib/appsmith/goss/appsmith.yaml
Labels: verify, bitnami

#75267 [bitnami/appsmith] Update GOSS tests for version 1.49.0 (part 2)
  .vib/appsmith/goss/appsmith.yaml
Labels: verify, bitnami

#75245 [bitnami/openldap] Renaming env variables as pointed in #19716
  bitnami/openldap/2.5/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh
  bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh
  bitnami/openldap/README.md
Labels: verify, in-progress, openldap

#75225 [bitnami/pgpool] Enhance pgpool-II Recovery Mechanism
  bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh
  bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/pgpool/run.sh
Labels: verify, in-progress, pgpool
